/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LGIEbxMvM9v
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import { useState } from "react";

export function navbarmovie() {
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const toggleSearch = () => setIsSearchOpen(!isSearchOpen);
  return (
    <header className="absolute w-full flex items-center justify-between h-20 px-4 md:px-6 border-b-0 bg-gradient-to-b from-neutral-950">
      <div className="flex items-center gap-14">
        <Link
          className="flex items-center gap-2 ml-1 text-lg font-semibold"
          href="#"
        >
          <FilmIcon className="w-8 h-8" />
          <span className="hidden xs:block">Ticketstubs</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6 text-sm font-medium lg:text-lg">
          <Link className="hover:underline" href="#">
            Top Rated
          </Link>
          <Link className="hover:underline" href="#">
            Popular
          </Link>
          <Link className="hover:underline" href="#">
            Genres
          </Link>
          <Link className="hover:underline" href="#">
            About
          </Link>
        </nav>
      </div>
      <div className="flex items-center gap-4">
        <Button
          className="group rounded-full"
          size="icon"
          variant="ghost"
          onClick={toggleSearch}
        >
          <>
            <SearchIcon className="w-5 h-5 text-white hover:text-gray-900" />
            <span className="sr-only">Search</span>
          </>
        </Button>
        <form
          className={`transition-all duration-100 ease-out overflow-hidden ${
            isSearchOpen ? "w-72" : "w-0"
          }`}
          onBlur={toggleSearch}
        >
          <Input
            type="text"
            className="flex flex-wrap rounded-full w-72 justify-center items-center"
            placeholder="Search..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
          <button type="submit" className="sr-only">
            Search
          </button>
        </form>
        <Button className="rounded-full" size="icon" variant="ghost">
          <img
            alt="Avatar"
            className="rounded-full"
            height="32"
            src="./placeholder-user.jpg"
            style={{
              aspectRatio: "32/32",
              objectFit: "cover",
            }}
            width="32"
          />
          <span className="sr-only">User Menu</span>
        </Button>
      </div>
    </header>
  );
}

function FilmIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className=" group-hover:text-gray-900"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

export default navbarmovie;
